ALTER TABLE users
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now();

ALTER TABLE users
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now();

ALTER TABLE users
    ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN created_at SET NOT NULL;